FROM mysql:8.0
LABEL maintainer="ucan-lab <yes@u-can.pro>"

ENV TZ=UTC \
  MYSQL_DATABASE=gym_app \
  MYSQL_USER=takahiro \
  MYSQL_PASSWORD=takahiro0119 \
  MYSQL_ROOT_PASSWORD=root

COPY ./my.cnf /etc/my.cnf
